version: "3.9"

services:
  go_app:
    container_name: go_app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      go_db:
        condition: service_healthy
        
  go_db:
    container_name: go_db
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5